# Site settings
title: Sudharsan Rajendran
twitter_username: sudhar1996
name: Rob Hinds

# Build settings
markdown: kramdown

#User specific content
#Links that will appear in the navbar
primarylinks:
 - title: Blog
   url: http://medium.com/@sudhar1996
 - title: GitHub
   url: https://github.com/Sudharsanrajendran
 - title: StackOverflow
   url: http://stackoverflow.com/users/3196851/sudhar
 - title: DZone
   url: https://dzone.com/users/2712104/sudhar1996.html
 - title: LinkedIn
   url: https://in.linkedin.com/in/sudhar1996

#Any buzzword skills you want to include
skills:
 - Programming
 - Web Development
 - Python
 - Agile Development
 - Java
 - Entrepreneurship
 
#Blogfeed is optional - including this will add JS to call the feed and populate blog list
blogfeed: http://automateddeveloper.blogspot.com/feeds/posts/default

#Work experience is required
roles:
 - title: Founder
   start: 2015
   end: Ongoing
   employer: CoderDojo Coimbatore
   description: Coimbatore CoderDojo is a free computer programming club for children. It is a Part of the world movement. We teach how to code, develop websites, apps, programs, games and explore technology in a formal and creative environment. In addition to learning code, attendees meet like minded people and are exposed to the possibilities of technology.
 - title: Ambassador
   start: 2013
   end: Ongoing
   employer: Mozilla
   description: I am responsible in organizing Mozilla events and workshops in our city. I am also participating as a speaker for the web awareness programs
 - title: Student Ambassador (Campus Crew)
   start: 2013
   end: Ongoing
   employer: Firefox
   description: Responsible for organizing web maker event and Web Literacy events
 - title: Motivatonal Speaker
   start: 2015
   end: Ongoing
   employer: CoderDojo Coimbatore @ KGISL
   description: Motivational speaker at CoderDojo and webmaker events. Motivating and inspiring young minds.

#Education is required
education:
 - level: Bachelor of Engineering (B.E.)
   date: 2017
   subject: Computer Science and Engineering
   school: KGiSL Institute of Techology

#List of interesting Github repo/projects to include - optional
github:
 - Sudharsanrajendran/Kinect-and-Sphero-Integration
 - Sudharsanrajendran/FoxIOT_meetup_materials
 - Sudharsanrajendran/A-simple-Search-Engine-in-Python
 - Sudharsanrajendran/AirPi
 - Sudharsanrajendran/Ghost
 - Sudharsanrajendran/YOURLS

#Stackoverflow flair is optional
stackoverflow:
   profileurl: http://stackoverflow.com/users/3196851/sudhar
   flairimageurl: http://stackoverflow.com/users/flair/3196851.png

#An additional info freetext section is optional at the bottom of the page - can be text or HTML
additionalinfo: |
   I am an outgoing and energetic (ask anybody) young professional, with professional skills, personality, and murderous tendencies. My squid-like head is a masterful problem solver and inspires fear in who gaze upon it. I can bring world domination to your organization.

